export {default as groups} from './groups/reducer';
export {default as lessonPlan} from './lesson-plan/reducer';
export {default as modals} from './modals/reducer';
export {default as subjects} from './subjects/reducer';
export {default as teachers} from './teachers/reducer';
export {default as groupTeachers} from './group-teachers/reducer';
export {default as audiences} from './audiences/reducer';
export {default as dynamicLessonPlan} from './dynamic-lesson-plan/reducer';
export {default as schedules} from './schedule/reducer'
export {default as lessonGroups} from './lesson-group/reducer'
export {default as teacherSubjects} from './teacher-subject/reducer'
export {default as parser} from './parser/reducer'